### ISSUE TITLE
Used inside routers

### ISSUE THREAD

**Issue by agmt5989** [CodingGangsta/express-rbac#2]
Bear with my approach, but I got it right up until `done(auth)`. The problem now is that my individual routes are 'used' in the main.js file by `app.use(route)`, which makes things quite complicated.

Importing `express-rbac` as `auth` in a route file and calling `auth.isInRole()` throws me a nasty little `TypeError: Cannot read property 'isInRole' of null` error in the console.

Please advise.

**Comment by ElChupi** [comment]
Mmm, don't quite understand what's the problem you are having. This library works the same way express does by itself, so you should be able to mix authorization on your routes without any changes on the design itself.
